name: WakeOnLan iOS Uygulama Derlemesi ve IPA Yayınlaması

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Uygulama Derlemesi
    runs-on: macos-latest

    steps:
      - name: Depoyu Çek (Ana Proje Kodu)
        uses: actions/checkout@v4

      - name: Theos Repository'yi Çek
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Theos SDK'larını Çek
        uses: actions/checkout@v4
        with:
          repository: theos/sdks
          ref: master
          path: theos/sdks

      - name: Gerekli Araçları Homebrew ile Yükle (ldid, make, xz, dpkg)
        run: |
          brew update
          brew install coreutils
          brew install make
          brew install xz
          brew install ldid
          brew install dpkg
        shell: bash

      - name: HATA AYIKLAMA:Theos Klasör İçeriğini Kontrol Et
        run: |
          echo "Theos klasörü içeriği (theos/):"
          ls -laR theos/
          echo "Theos makefiles klasörü içeriği (theos/makefiles/):"
          ls -la theos/makefiles/
        shell: bash

      - name: HATA AYIKLAMA:Proje Makefile İçeriğini Kontrol Et
        run: |
          echo "Projenizin Makefile içeriği:"
          # Projenizin Makefile'ı deponun kökünde DEĞİLSE, yolu doğru ayarlayın.
          # Örneğin, 'WakeOnLanApp/Makefile' ise: 'cat WakeOnLanApp/Makefile'
          cat Makefile
        shell: bash

      - name: Theos Projesini Derle
        run: |
          export THEOS="<span class="math-inline">\(pwd\)/theos"
