name: WakeOnLan iOS Uygulama Derlemesi ve IPA Yayınlaması

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Uygulama Derlemesi
    runs-on: macos-latest

    steps:
      - name: Depoyu Çek (Ana Proje Kodu)
        uses: actions/checkout@v4

      - name: Theos Repository'yi Çek
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Theos SDK'larını Çek
        uses: actions/checkout@v4
        with:
          repository: theos/sdks
          ref: master
          path: theos/sdks

      - name: Gerekli Araçları Homebrew ile Yükle (ldid, make, xz, dpkg)
        run: |
          brew update
          brew install coreutils
          brew install make
          brew install xz
          brew install ldid
          brew install dpkg
        shell: bash

      - name: Theos Projesini Derle
        run: |
          export THEOS=theos
          
          # DİKKAT: Projenizin konumu için aşağıdaki satırı ayarlayın!
          # EĞER "Makefile", "main.m" gibi dosyalar doğrudan "wakeonlanipa" deponuzun ana klasöründeyse,
          # aşağıdaki "cd wakeonlanipa" satırını SİLİN veya YORUM SATIRI YAPIN (# koyarak).
          # EĞER bu dosyalar deponun içinde "WakeOnLanApp" veya "myApp" gibi bir alt klasördeyse,
          # aşağıdaki "cd" komutunu o ALT KLASÖRÜN ADIYLA GÜNCELLEYİN.
          # Örnek: "cd WakeOnLanApp" veya "cd myApp"
          # Eğer projeniz doğrudan depoda ise, bu satıra ihtiyacınız yoktur.
          # cd <BURAYA_PROJE_KLASÖRÜ_ADINIZI_YAZIN_VEYA_SİLİN>
          
          gmake package FINALPACKAGE=1 STRIP=0
        shell: bash

      - name: IPA Dosyasını .deb Paketinden Çıkar
        run: |
          export THEOS=theos
          
          # DİKKAT: Projenizin konumu için aşağıdaki satırı ayarlayın!
          # Üstteki "Theos Projesini Derle" adımındaki ayarınızla AYNI olmalı.
          # Eğer üstte "cd" komutunu sildiyseniz, burada da silin.
          # cd <BURAYA_PROJE_KLASÖRÜ_ADINIZI_YAZIN_VEYA_SİLİN>

          DEB_FILE=$(find packages -name "*.deb" | head -n 1)

          if [ -z "$DEB_FILE" ]; then
            echo "Hata: .deb dosyası bulunamadı. Derleme başarısız olmuş olabilir."
            exit 1
          fi

          echo "Bulunan .deb dosyası: $DEB_FILE"

          mkdir -p temp_extract
          ar x "$DEB_FILE" -C temp_extract
          tar -xf temp_extract/data.tar.xz -C extracted_ipa

          APP_BUNDLE_PATH=$(find extracted_ipa/Applications -type d -name "*.app" | head -n 1)

          if [ -z "$APP_BUNDLE_PATH" ]; then
            echo "Hata: .app bundle'ı extracted_ipa/Applications içinde bulunamadı."
            exit 1
          fi

          echo "Bulunan .app bundle: $APP_BUNDLE_PATH"

          mkdir -p final_ipa/Payload
          mv "$APP_BUNDLE_PATH" final_ipa/Payload/

          zip -r "../wakeonlanipa-${{ github.sha }}.ipa" final_ipa/* # IPA dosyasının adını depo adınla eşleştirdim

          echo "IPA dosyası oluşturuldu: wakeonlanipa-${{ github.sha }}.ipa"
        shell: bash

      - name: Derlenmiş IPA'yı Yayınla (Artifact Olarak Yükle)
        uses: actions/upload-artifact@v4
        with:
          name: wakeonlanipa-IPA
          path: wakeonlanipa-${{ github.sha }}.ipa # IPA dosyasının adını depo adınla eşleştirdim
          retention-days: 7